'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace GabineteAbogadosApp

    Partial Public Class GaAbogadosEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=GaAbogadosEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Procurador() As DbSet(Of Procurador)
        Public Overridable Property TipoAsuntos() As DbSet(Of TipoAsuntos)
    
    End Class

End Namespace
