'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace GabineteAbogadosApp

    Partial Public Class Procurador
        Public Property UserID As Integer
        Public Property DNI As String
        Public Property LoginName As String
        Public Property Password As String
        Public Property FirstName As String
        Public Property LastName As String
        Public Property Position As String
        Public Property Email As String
        Public Property Telephone As String
    
    End Class

End Namespace
